[info]
typeName = "std::pair<"
numTemplateParams = 2
ctype = "PAIR_TYPE"
header = "utility"
ns = ["namespace std"]
replaceTemplateParamIndex = []
# allocatorIndex = 0
# underlyingContainerIndex = 0

[codegen]
decl = """
template<typename P, typename Q>
void getSizeType(const %1%<P,Q> &p, size_t& returnArg);
"""

func = """
template<typename P, typename Q>
void getSizeType(const %1%<P,Q> &p, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<P,Q>) - sizeof(P) - sizeof(Q));

    getSizeType(p.first, returnArg);
    getSizeType(p.second, returnArg);
}
"""
